// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.startupRolloutPrefs.extensions.blocklist.useMLBF", true);
user_pref("app.normandy.startupRolloutPrefs.extensions.blocklist.useMLBF.stashes", true);
user_pref("app.normandy.user_id", "f8a23bd7-03ae-4bac-9223-d5f7e894f2e1");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1597832733);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1597832707);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1597832973);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1597832853);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1597832763);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 51200);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1597832703);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.impressionId", "{b0b4ad7e-958a-4538-b3bf-b28aa6c82c22}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1597832745834");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1597834534834");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1597832706771");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1597836306771");
user_pref("browser.search.region", "PL");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1597832705");
user_pref("browser.slowStartup.averageTime", 5723);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20200727193539");
user_pref("browser.startup.homepage_override.mstone", "79.0");
user_pref("browser.startup.lastColdStartupCheck", 1597832705);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1597832706140");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "79.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "83ee0ed38f174f9894c91e6cd6166811");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "79.0");
user_pref("extensions.lastPlatformVersion", "79.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"9dd1131e-beee-46e1-acf0-c3bf8cb72fa7\",\"formautofill@mozilla.org\":\"7042accb-2c11-4513-b057-05beb80f7bf5\",\"screenshots@mozilla.org\":\"7c3840a3-4539-485a-bffa-28fbf245304f\",\"webcompat-reporter@mozilla.org\":\"e34cb6fa-7d62-486b-85ce-b3f3df1e5015\",\"webcompat@mozilla.org\":\"0d47d983-ecd8-4bd4-b808-4e0edef01ec4\",\"default-theme@mozilla.org\":\"92585b4e-9b63-4d67-884e-098381fb1b65\",\"google@search.mozilla.org\":\"f4caeb78-4824-417a-bdb9-b0bff918efc2\",\"amazondotcom@search.mozilla.org\":\"a83b9a7f-a381-46a9-acfa-e25003c20aa3\",\"wikipedia@search.mozilla.org\":\"1c2155a0-d3be-4e30-b985-6353036f3f57\",\"bing@search.mozilla.org\":\"d697bab2-ab49-4366-959e-11d1eb2a3a39\",\"ddg@search.mozilla.org\":\"e8fa9dac-e5aa-4dd0-a3f3-0f275df1dd10\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1597832763);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20200727193539");
user_pref("media.gmp-manager.lastCheck", 1597832763);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 6552);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.remote_settings.crlite_filters.checked", 1597832726);
user_pref("security.remote_settings.intermediates.checked", 1597832726);
user_pref("security.sandbox.content.tempDirSuffix", "11b3c121-60a8-48f8-9a2d-6e937fd8b380");
user_pref("security.sandbox.plugin.tempDirSuffix", "7af41db0-6f51-4b11-8983-943cef94ea60");
user_pref("services.blocklist.addons-mlbf.checked", 1597832726);
user_pref("services.blocklist.addons.checked", 1597832726);
user_pref("services.blocklist.gfx.checked", 1597832726);
user_pref("services.blocklist.pinning.checked", 1597832726);
user_pref("services.blocklist.plugins.checked", 1597832726);
user_pref("services.settings.clock_skew_seconds", 36);
user_pref("services.settings.last_etag", "\"1597797637746\"");
user_pref("services.settings.last_update_seconds", 1597832726);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1597832726);
user_pref("services.settings.main.cfr-fxa.last_check", 1597832726);
user_pref("services.settings.main.cfr.last_check", 1597832726);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1597832726);
user_pref("services.settings.main.hijack-blocklists.last_check", 1597832726);
user_pref("services.settings.main.language-dictionaries.last_check", 1597832726);
user_pref("services.settings.main.message-groups.last_check", 1597832726);
user_pref("services.settings.main.messaging-experiments.last_check", 1597832726);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1597832726);
user_pref("services.settings.main.pioneer-study-addons.last_check", 1597832726);
user_pref("services.settings.main.public-suffix-list.last_check", 1597832726);
user_pref("services.settings.main.search-config.last_check", 1597832726);
user_pref("services.settings.main.search-default-override-allowlist.last_check", 1597832726);
user_pref("services.settings.main.sites-classification.last_check", 1597832726);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1597832726);
user_pref("services.settings.main.whats-new-panel.last_check", 1597832726);
user_pref("services.settings.security.onecrl.checked", 1597832726);
user_pref("toolkit.startup.last_success", 1597832700);
user_pref("toolkit.telemetry.cachedClientID", "a3f4d6e7-a62a-43f0-9955-6d111617082b");
user_pref("toolkit.telemetry.pioneer-new-studies-available", true);
user_pref("toolkit.telemetry.previousBuildID", "20200727193539");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
